SettingScreen As screen:
    Fill: =RGBA(240,239,228,1)

    SettingScreenCheckbox As checkbox:
        Height: =80
        Size: =21
        Text: ="保護者アカウントと結びつける"
        Visible: =Not(is_parent)
        Width: =475
        X: =106
        Y: =60
        ZIndex: =1

    SettingScreenParentUser As text:
        Default: =""
        Height: =70
        HintText: ="保護者のユーザー名"
        Size: =21
        Visible: =SettingScreenCheckbox.Value
        Width: =560
        X: =21
        Y: =233
        ZIndex: =2

    SettingScreenParentPassword As text:
        Default: =""
        Height: =70
        HintText: ="保護者のパスワード"
        Mode: =TextMode.Password
        Size: =21
        Visible: =SettingScreenCheckbox.Value
        Width: =560
        X: =21
        Y: =397
        ZIndex: =3

    SettingScreenSubmitButton As button:
        Height: =70
        OnSelect: |-
            =Set(
                tmp,
                LookUp(
                    B_USER,
                    And(USERNAME = SettingScreenParentUser.Text, PASSWORD = SettingScreenParentPassword.Text, FLAG = "P")
                )
            );
            If(
                IsBlank(tmp),
                Notify("保護者アカウントと結びつけるのに失敗しました。保護者のユーザー名とパスワードを再確認してください。", NotificationType.Error),
                /*
                Set(tmp_username, LookUp(B_USER, USERID = Text(user_id)).USERNAME);
                Set(tmp_password, LookUp(B_USER, USERID = Text(user_id)).PASSWORD);
                */
                Patch(
                    B_USER,
                    LookUp(
                        B_USER,
                        USERID = Text(user_id)
                    ),
                    {
                        hws_username: user_name,
                        hws_password: user_password,
                        FLAG: "C",
                        PARENTID: Int(tmp.USERID)
                    }
                );
                Notify("連携しました", NotificationType.Success);
                Navigate(HomeScreen,ScreenTransition.None)
            );
        Size: =24
        Text: ="承認する"
        Visible: =SettingScreenCheckbox.Value
        Width: =280
        X: =161
        Y: =586
        ZIndex: =4

    SettingScreenBackIcon As icon.ArrowLeft:
        Icon: =Icon.ArrowLeft
        OnSelect: =Back()
        ZIndex: =7

    SettingScreenInformationLabel As label:
        Height: =156
        Size: =20
        Text: |-
            ="Created by DICE
            
            
            Powered by PowerApps"
        Width: =319
        X: =21
        Y: =965
        ZIndex: =8

    SettingScreenDICEiconImage As image:
        Height: =116
        Image: =DICE_icon
        Width: =116
        X: =441
        Y: =985
        ZIndex: =9

